name: Beta Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 8
          check-latest: true
      - name: Set version
        run: |
          echo "VERSION=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Config repo
        run: python config_version.py
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk8
          arguments: build --no-build-cache
          gradle-version: wrapper
      - name: Prepare artifact
        run: |
          cd build/libs
          zip minusbounce.zip *
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MinutBau
          path: build/libs/minusbounce.zip
